### ISSUE TITLE
Script Failed to start on QBCore

### ISSUE THREAD

**Issue by SirOMGitsYOU** [troner14/reportSystem#1]
Hey - 

When trying to start this script on QBCore it throws a bunch of errors-

https://pastes.dev/cGTd0W0DRN

**Comment by Mat40** [comment]
QBCore.RegisterCommand don't exist in docs 
https://docs.qbcore.org/qbcore-documentation/?q=registercommand

**Comment by troner14** [comment]
Under script use 
![Uploading Screenshot_2023-05-03-19-21-45-148_com.brave.browser.png…]()

**Comment by troner14** [comment]
@
![Screenshot_2023-05-03-19-21-45-148_com brave browser](https://user-images.githubusercontent.com/73949396/235993502-652be442-6cf3-4f81-9fd4-b08a2c55187f.png)

**Comment by troner14** [comment]
try now with last update

**Comment by SirOMGitsYOU** [comment]
Looks to be all working now thank you very much @troner14
