### ISSUE TITLE
toggle reports no funciona

### ISSUE THREAD

**Issue by druf0** [troner14/reportSystem#8]
Al usar /togglereports en ESX, solamente te muestra el mensaje de que se desactivan los reports, no el de que se activan.
Además, los usuarios no pueden utilizar el comando porque les sale acceso denegado.

**Comment by troner14** [comment]
creo que esta solucionado. estoy teniendo problemas con fivem y no puedo comprobar-lo

**Comment by troner14** [comment]
yes is fixed
